- name: Provision all OpenStack instances
  hosts: localhost
  connection: local
  gather_facts: no
  # become: no
  vars:
    config_file: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    clouds:
      devstack:
        auth_url: "{{lookup('env', 'OS_AUTH_URL')}}"
        username: "{{lookup('env', 'OS_USERNAME')}}"
        password: "{{lookup('env', 'OS_PASSWORD')}}"
        project_name: "{{lookup('env', 'OS_PROJECT_NAME')}}"

  tasks:
    - name: launch an instance
      debug:
        # msg: "{{ auth_url }} - {{ username }} - {{ password }} - {{ project_name }}"
        msg: "{{ clouds }} "
    - name: Env VARS
      debug:
        msg: "{{ lookup('env', 'OS_CLIENT_CONFIG_FILE') }}"
    - include_vars: "{{ config_file }}"
    - name: Print configuration file
      debug:
        msg: "{{ clouds }}"
    - name: Print some debug information 
      vars: 
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }} 
          
          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }} 
          
          GROUP NAMES Variables ("group_names"):
          --------------------------------
          {{ group_names | to_nice_json }}
          
          GROUPS Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}
          
          HOST Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }} 
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
